version: '3'
services:
  web:
    stdin_open: true
    image: docker-react-app-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src