name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Pull Docker image
      run: podman docker pull soufiane001/cicd-pipeline:latest
    - name: Delete Old docker container
      run: podman docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: podman docker run -d -p 8080:8080 --name cicd-pipeline-container soufiane001/cicd-pipeline
